baseURL = 'https://intelligeneer.github.io'
languageCode = 'en-us'
title = 'Intelligeneer BUG BS ğŸ¤' #ä½ å¦ˆçš„å‚»é€¼å®¢äºº
theme = 'paper'

enableInlineShortcodes = 'true' #å…è®¸å†…è”çŸ­ç 
enableEmoji = 'true'   #å…è®¸ä½¿ç”¨ Emoji è¡¨æƒ…ï¼Œå»ºè®® true
enableRobotsTXT = 'true' #å…è®¸çˆ¬è™«æŠ“å–åˆ°æœç´¢å¼•æ“ï¼Œå»ºè®® true
hasCJKLanguage = 'true' #è‡ªåŠ¨æ£€æµ‹æ˜¯å¦åŒ…å« ä¸­æ–‡æ—¥æ–‡éŸ©æ–‡ å¦‚æœæ–‡ç« ä¸­ä½¿ç”¨äº†å¾ˆå¤šä¸­æ–‡å¼•å·çš„è¯å¯ä»¥å¼€å¯

buildDrafts = 'false'
buildFuture = 'false'
buildExpired = 'false'

[menu]
[[menu.main]]
identifier = "ä¸­æ–‡"
name = "ä¸­æ–‡/ğŸ‡¨ğŸ‡³"
url = "/cn"
weight = 1

[[menu.main]]
identifier = "English"
name = "English/ğŸ‡¦ğŸ‡º"
url = "/en"
weight = 2

[[menu.main]]
identifier = "Internal Use"
name = "ğŸ—ƒï¸Internal Use"
url = "/Internal_Use/"
weight = 3

[[menu.main]]
identifier = "About"
name = "ğŸ˜˜About Us"
url = "/about/"
weight = 4


[params]
author = "Intelligeneer Soltuion"
description = "There need to be add description"
#twitter = ''                # twitter.com/YOUR_TWITTER_ID
#   github = ''                  # github.com/YOUR_GITHUB_ID
instagram = 'ada_pay_'            # instagram.com/YOUR_INSTAGRAM_ID
avatar = "https://www.intelligeneer.com/cdn/shop/files/Screen_Shot_2022-04-28_at_11.08.37_AM.png?v=1651108130"

[taxonomies]
tag = "tags"

[assets]
favicon = "img/appe-touch-icon.png"
favicon16x16 = "img/appe-touch-icon.png"
favicon32x32 = "img/appe-touch-icon.png"
apple_touch_icon = "img/appe-touch-icon.png"
safari_pinned_tab = "img/appe-touch-icon.png"

